# Generated by Django 4.2.5 on 2023-11-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_alter_user_date_joined_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='shayan', max_length=10),
            preserve_default=False,
        ),
    ]
