# Generated by Django 4.2.5 on 2023-11-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_alter_user_date_joined_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(default="'https://www.linkedin.com/in/shayan-tehrani/'"),
            preserve_default=False,
        ),
    ]
