# Generated by Django 4.2.5 on 2023-11-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_user_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
