# Generated by Django 4.2.5 on 2023-11-21 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
