# Generated by Django 4.2.5 on 2023-11-23 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0010_component_alter_portfolio_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroComponent',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='controller.component')),
                ('description', models.TextField()),
            ],
            bases=('controller.component',),
        ),
        migrations.CreateModel(
            name='IterableComponent',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='controller.component')),
                ('iterable_html', models.TextField()),
            ],
            bases=('controller.component',),
        ),
        migrations.RemoveField(
            model_name='component',
            name='type',
        ),
        migrations.CreateModel(
            name='EducationComponent',
            fields=[
                ('iterablecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='controller.iterablecomponent')),
            ],
            bases=('controller.iterablecomponent',),
        ),
        migrations.CreateModel(
            name='PortfolioComponent',
            fields=[
                ('iterablecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='controller.iterablecomponent')),
            ],
            bases=('controller.iterablecomponent',),
        ),
        migrations.CreateModel(
            name='SkillsComponent',
            fields=[
                ('iterablecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='controller.iterablecomponent')),
            ],
            bases=('controller.iterablecomponent',),
        ),
        migrations.CreateModel(
            name='WorkComponent',
            fields=[
                ('iterablecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='controller.iterablecomponent')),
            ],
            bases=('controller.iterablecomponent',),
        ),
    ]
