# Generated by Django 4.2.5 on 2023-11-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0011_introcomponent_iterablecomponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='css',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
