# Generated by Django 4.2.5 on 2023-11-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0013_website_rename_css_component_theme_component_preview_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitecomponentorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='websitecomponentorder',
            name='order',
        ),
    ]
