# Generated by Django 4.2.5 on 2023-11-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0016_user_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introcomponent',
            name='description',
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='this is me, I am super cool and funny'),
            preserve_default=False,
        ),
    ]
