# Generated by Django 4.2.5 on 2023-11-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0017_remove_introcomponent_description_user_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='theme',
        ),
        migrations.AddField(
            model_name='websitecomponentorder',
            name='theme',
            field=models.CharField(default='#a87932', max_length=255),
            preserve_default=False,
        ),
    ]
