# Generated by Django 4.2.5 on 2023-11-30 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0018_remove_component_theme_websitecomponentorder_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecomponentorder',
            name='theme',
            field=models.CharField(default='#0d00fc', max_length=255),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('design', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
