# Generated by Django 4.2.5 on 2023-12-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0020_alter_feedback_design_alter_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='employment_type',
            field=models.CharField(choices=[('Self-employed', 'Self-employed'), ('Freelance', 'Freelance'), ('Internship', 'Internship'), ('Full time', 'Full time'), ('Part time', 'Part time'), ('Contract', 'Contract'), ('Co op', 'Co op'), ('Seasonal', 'Seasonal')], default='Full time', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='industry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='skills',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
